### ISSUE TITLE
Readme.rst conflicts

### ISSUE THREAD

**Issue by scemama** [LCPQ/quantum_package#100]
Automatic build of Readme.rst should be done only for the LCPQ branch. Forks should not automatically update Readme.rst because there are lots of conflicts durin merges.
```
REPO=$( git config --get remote.origin.url | cut -d ':' -f 2 )
```
should be ``LCPQ/quantum_package.git`` . If not, ``update_readme.py`` should do nothing.

**Comment by TApplencourt** [comment]
All the documentation handle (coherency, merging, update) are really
treaky. I'm open to any suggestion to improve it.

My main concern about the LCPQ only documention update is than the
documentation will never be update.  (we will forget to update the
documentation in this repo).

I change many stuff in the documentation in this commit  (aka the order off
needed children section and irp documentation has not coherent in all the
module), maybe this cause the conflict.

For solving all the doc conflict in once a (i haven't testing yet)
grep -lr '<<<<<<<' .| grep -i readme.rst| xargs git checkout --theirs

Should do the trick.

Nether the both solutions are perfect sadly.

Maybe we need to use a vm. with a hook on LCPQ commits that trigger the
update of the documentation. It will ensure the coherency of the
documentation.

It's a little bit of work, but  'ça vaudrait peut-être le coup'.

Automatic build of Readme.rst should be done only for the LCPQ branch.
Forks should not automatically update Readme.rst because there are lots of
conflicts durin merges.

REPO=$( git config --get remote.origin.url | cut -d ':' -f 2 )

should be LCPQ/quantum_package . If not, update_readme.py should do nothing.

—
Reply to this email directly or view it on GitHub
<https://github.com/LCPQ/quantum_package/issues/100>.
