### ISSUE TITLE
ocamlfind: Package `sexplib.syntax' not found

### ISSUE THREAD

**Issue by artemgru** [LCPQ/quantum_package#183]
hi all!
My ocaml version is 4.0.4

My core library is:
ocamlfind list | grep core
core                (version: 113.33.02+4.03)
core.syntax         (version: [deprecated])
core.top            (version: 113.33.02+4.03)
core_kernel         (version: 113.33.01+4.03)
num.core            (version: [internal])
ppx_core            (version: 113.33.01+4.03)

So I am getting this error:
ocamlfind: Package `sexplib.syntax' not found

I saw that this problem is possible to earlier version of core library.But I have the latest one.
Could you help me to fix it?!
It very important for me!

**Comment by scemama** [comment]
Hi,
the simplest and most efficient method is to completely remove your OCaml installation and let the configure script install the latest one. It wil take time, but it will work. To do this, remove the `$HOME/.opam` directory.

**Comment by artemgru** [comment]
The problem is I have a machine without Internet connection,so **opam install** isn't an option for me.that is why I installed ocaml and core library manually.

**Comment by scemama** [comment]
Your problem is an incompability of versions between the OCaml compiler and the latest core library. I never installed it by hand, always with opam. Try to post an issue on the Core library GitHub page.

You can also install everything on a machine with an internet connection, the copy the `$HOME/.opam` directory on a USB stick to copy it on the other machine without the internet connection. It should work.
